# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-01 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('access_token', models.CharField(editable=False, max_length=30)),
                ('post_channel', models.CharField(default=None, max_length=21)),
                ('approval_channel', models.CharField(default=None, max_length=21)),
                ('admin_only_approval', models.BooleanField(default=True)),
                ('admin_only_edit', models.BooleanField(default=True)),
            ],
        ),
    ]
