# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='access_token',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
