# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_team_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='backup_channel',
            field=models.CharField(default=None, max_length=21),
        ),
    ]
