# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_team_backup_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='backup_channel',
            field=models.CharField(default=None, max_length=21, null=True),
        ),
    ]
