# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-14 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170103_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='backup_channel',
        ),
    ]
